# Generated by Django 6.0.3 on 2026-03-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0002_destination"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="destinations",
            field=models.ManyToManyField(blank=True, related_name="company_users", to="destinations.destination"),
        ),
    ]
