# Generated by Django 6.0.3 on 2026-03-16 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("visitor_name", models.CharField(max_length=150)),
                ("plate", models.CharField(max_length=20)),
                (
                    "pass_type",
                    models.CharField(
                        choices=[("single", "Single Use"), ("day", "Day Pass")], default="day", max_length=20
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_passes",
                        to="destinations.destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Pass",
                "verbose_name_plural": "Access Passes",
                "ordering": ["-created_at"],
            },
        ),
    ]
