# Generated by Django 6.0.3 on 2026-03-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspass",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
