# Generated by Django 6.0.3 on 2026-04-10 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
        ("destinations", "0002_initial"),
        ("passes", "0002_add_is_used_to_access_pass"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(fields=["entry_time"], name="accesslog_entry_time_idx"),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(fields=["status"], name="accesslog_status_idx"),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(fields=["destination", "entry_time"], name="accesslog_dest_entry_idx"),
        ),
    ]
